import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        // Overview Section
        'overview',

        // Section Title: Data Connections
        {
            type: 'html',
            value: '<div class="sidebar-title">Integrating with Subsets?</div>',
            defaultStyle: true,
        },
        {
            type: 'category',
            label: 'Data Connections',
            collapsed: true,
            items: [
                {type: 'autogenerated', dirName: 'Data Connections'},
            ],
        },

        // Data Delivery Section
        {
            type: 'category',
            label: 'Data Delivery',
            collapsed: true,
            items: [
                {type: 'autogenerated', dirName: 'Data Delivery'},
            ],
        },

        {
            type: 'category',
            label: 'Integrations',
            collapsed: true,
            items: [
                {type: 'autogenerated', dirName: 'Integrations'},
            ],
        },
        // Section Title: Platform
        {
            type: 'html',
            value: '<div class="sidebar-title">Using the Subsets platform?</div>',
            defaultStyle: true,
        },
        {
            type: 'category',
            label: 'Experiment Creation',
            collapsed: true,
            items: [
                {type: 'autogenerated', dirName: 'Experiment Creation'},
            ],
        },
    ],
};

export default sidebars;
